import Foundation

/// The top-level entry point for the GitTickets SDK.
///
/// Call ``configure(_:)`` once at app launch with a ``Configuration`` describing
/// the GitHub repository submissions should land in and the authentication mode
/// to use. After configuration, present ``GitTicketsCommands`` (SwiftUI) or
/// `GitTicketsMenuItemFactory` (AppKit) to give end-users a "Report an Issue" surface.
///
/// ```swift
/// GitTickets.configure(.init(
///     repo: .init(owner: "alanw", name: "MyApp", visibility: .public),
///     auth: .relay(url: relayURL, sharedSecret: secret)
/// ))
/// ```
public enum GitTickets {

    /// Configures the SDK. Idempotent — the most recent call wins.
    ///
    /// Call this once at app launch (or as early as you have the repo coordinates
    /// and auth mode). Subsequent calls replace the active configuration.
    ///
    /// - Parameter configuration: The active configuration.
    public static func configure(_ configuration: Configuration) {
        configurationStorage.set(configuration)
    }

    /// The active configuration, or `nil` if ``configure(_:)`` has not been called.
    public static var configuration: Configuration? {
        configurationStorage.get()
    }

    /// Submits a report through the configured auth mode.
    ///
    /// Most apps don't call this directly — use ``GitTicketsView``,
    /// ``GitTicketsCommands``, or `GitTicketsMenuItemFactory` instead. This entry
    /// point exists for hosts that ship their own UI and want only the submission
    /// pipeline.
    ///
    /// Pipeline:
    /// 1. Reads ``configuration``; throws ``GitTicketsError/notConfigured`` if
    ///    ``configure(_:)`` hasn't been called.
    /// 2. Fills `report.deviceID` from the per-install ``DeviceIdentity`` when
    ///    blank, so per-device rate limiting and Phase 2 "My Issues"
    ///    correlation work even when the caller didn't supply one.
    /// 3. Resolves the active ``AuthMode`` to a submitter (``RelaySubmitter``
    ///    for `.relay`; a Device Flow submitter lands in PR 11).
    /// 4. Forwards to the submitter, which uploads attachments, assembles the
    ///    body, POSTs to GitHub (via relay), and writes the result into the
    ///    shared ``SubmissionCache``.
    ///
    /// - Parameter report: The report to submit. ``Report/submissionID`` is
    ///   generated by the SDK by default; ``Report/deviceID`` is filled from
    ///   the per-install Keychain identifier when blank.
    /// - Returns: A ``SubmittedIssue`` describing the created GitHub issue.
    /// - Throws: ``GitTicketsError`` — `.notConfigured` if configure hasn't
    ///   been called; the submitter's own errors otherwise.
    @discardableResult
    public static func submit(_ report: Report) async throws -> SubmittedIssue {
        guard let configuration else { throw GitTicketsError.notConfigured }
        var report = report
        if report.deviceID.isEmpty {
            report.deviceID = currentDeviceID(logger: configuration.logger)
        }
        let submitter = try resolveSubmitter(configuration: configuration)
        return try await submitter.submit(report)
    }

    // MARK: - Internal storage

    /// Resets the active configuration. Test-only.
    static func _resetConfigurationForTesting() {
        configurationStorage.set(nil)
        cacheStorage.reset()
    }

    private static let configurationStorage = ConfigurationStorage()
    private static let cacheStorage = SubmissionCacheStorage()

    // MARK: - Helpers

    /// Resolves the active ``AuthMode`` into a submitter. Production code
    /// hits the relay path; ``AuthMode/deviceFlow(clientID:scopes:)`` lands
    /// in PR 11; ``AuthMode/mock`` is test-only.
    private static func resolveSubmitter(
        configuration: Configuration
    ) throws -> any IssueSubmitter {
        switch configuration.auth {
        case .relay:
            guard let submitter = RelaySubmitter(
                configuration: configuration,
                cache: cacheStorage.shared(logger: configuration.logger)
            ) else {
                throw GitTicketsError.notConfigured
            }
            return submitter
        case .deviceFlow:
            throw GitTicketsError.payloadInvalid(
                reason: "Device Flow submitter ships in PR 11."
            )
        case .mock:
            throw GitTicketsError.payloadInvalid(
                reason: "AuthMode.mock has no production submitter."
            )
        }
    }

    /// Reads or generates the stable per-install identifier. Failures fall
    /// back to a blank string and log a warning — the rest of the pipeline
    /// still works (per-device rate limiting just won't track this device)
    /// rather than blocking on Keychain issues during local dev.
    private static func currentDeviceID(logger: GitTicketsLogger?) -> String {
        do {
            return try DeviceIdentity().currentOrGenerate()
        } catch {
            logger?.log(
                level: .warning,
                message: "Could not read or generate per-install device identifier; submitting with a blank deviceID.",
                error: error
            )
            return ""
        }
    }
}

/// Lazily opens the production-default ``SubmissionCache`` so the first
/// submit() call doesn't pay the file-system cost during app launch and a
/// failed open doesn't take the whole SDK out of action.
private final class SubmissionCacheStorage: @unchecked Sendable {
    private let lock = NSLock()
    private var cache: SubmissionCache?
    private var failedToOpen = false

    func shared(logger: GitTicketsLogger?) -> SubmissionCache? {
        lock.lock()
        defer { lock.unlock() }
        if let cache { return cache }
        if failedToOpen { return nil }
        do {
            let url = try SubmissionCache.defaultDatabaseURL()
            let opened = try SubmissionCache(databaseURL: url)
            cache = opened
            return opened
        } catch {
            failedToOpen = true
            logger?.log(
                level: .warning,
                message: "Could not open SubmissionCache at the default path; 'My Issues' will be empty until the next launch.",
                error: error
            )
            return nil
        }
    }

    func reset() {
        lock.lock()
        cache = nil
        failedToOpen = false
        lock.unlock()
    }
}

/// Thread-safe holder for the active ``Configuration``.
///
/// `Configuration` is a non-trivial value type containing a `URL`, a
/// `SharedSecret` (Data), and several policy structs. Assignment is not
/// atomic, so concurrent `configure(_:)` and `configuration` access would
/// race if we stored it in a bare `nonisolated(unsafe) static var`. Wrapping
/// the read/write in an `NSLock` makes both publish/consume atomic.
private final class ConfigurationStorage: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Configuration?

    func get() -> Configuration? {
        lock.lock()
        defer { lock.unlock() }
        return value
    }

    func set(_ value: Configuration?) {
        lock.lock()
        self.value = value
        lock.unlock()
    }
}
