import Foundation

/// The top-level entry point for the GitTickets SDK.
///
/// Call ``configure(_:)`` once at app launch with a ``Configuration`` describing
/// the GitHub repository submissions should land in and the authentication mode
/// to use. After configuration, present ``GitTicketsCommands`` (SwiftUI) or
/// `GitTicketsMenuItemFactory` (AppKit) to give end-users a "Report an Issue" surface.
///
/// ```swift
/// GitTickets.configure(.init(
///     repo: .init(owner: "alanw", name: "MyApp", visibility: .public),
///     auth: .relay(url: relayURL, sharedSecret: secret)
/// ))
/// ```
///
/// > Skeleton release. Auth submitters, UI, and storage land in later PRs;
/// > the entry point currently throws ``GitTicketsError/notConfigured`` from
/// > ``submit(_:)`` regardless of configuration.
public enum GitTickets {

    /// Configures the SDK. Idempotent — the most recent call wins.
    ///
    /// Call this once at app launch (or as early as you have the repo coordinates
    /// and auth mode). Subsequent calls replace the active configuration.
    ///
    /// - Parameter configuration: The active configuration.
    public static func configure(_ configuration: Configuration) {
        configurationStorage.set(configuration)
    }

    /// The active configuration, or `nil` if ``configure(_:)`` has not been called.
    public static var configuration: Configuration? {
        configurationStorage.get()
    }

    /// Submits a report through the configured auth mode.
    ///
    /// Most apps don't call this directly — use ``GitTicketsView``,
    /// ``GitTicketsCommands``, or `GitTicketsMenuItemFactory` instead. This entry
    /// point exists for hosts that ship their own UI and want only the submission
    /// pipeline.
    ///
    /// - Parameter report: The report to submit. ``Report/submissionID`` and
    ///   ``Report/deviceID`` are generated by the SDK when not provided by the
    ///   convenience initializer.
    /// - Returns: A ``SubmittedIssue`` describing the created GitHub issue.
    /// - Throws: ``GitTicketsError`` — in this skeleton, always `.notConfigured`.
    @discardableResult
    public static func submit(_ report: Report) async throws -> SubmittedIssue {
        throw GitTicketsError.notConfigured
    }

    // MARK: - Internal storage

    /// Resets the active configuration. Test-only.
    static func _resetConfigurationForTesting() {
        configurationStorage.set(nil)
    }

    private static let configurationStorage = ConfigurationStorage()
}

/// Thread-safe holder for the active ``Configuration``.
///
/// `Configuration` is a non-trivial value type containing a `URL`, a
/// `SharedSecret` (Data), and several policy structs. Assignment is not
/// atomic, so concurrent `configure(_:)` and `configuration` access would
/// race if we stored it in a bare `nonisolated(unsafe) static var`. Wrapping
/// the read/write in an `NSLock` makes both publish/consume atomic.
private final class ConfigurationStorage: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Configuration?

    func get() -> Configuration? {
        lock.lock()
        defer { lock.unlock() }
        return value
    }

    func set(_ value: Configuration?) {
        lock.lock()
        self.value = value
        lock.unlock()
    }
}
