import Foundation

/// The category of report being filed.
///
/// Drives the default body template (e.g. "Steps to reproduce" for `.bug`,
/// "Problem to solve" for `.featureRequest`) and the labels applied to the
/// resulting GitHub issue.
public enum ReportKind: String, Sendable, Hashable, CaseIterable, Codable {
    case bug
    case featureRequest = "feature_request"
    case question
}

/// A single attachment included with a ``Report``.
///
/// Currently used for inline images (PNG, JPEG, HEIC). Other types are
/// rejected by the relay in v1.
public struct ReportAttachment: Sendable, Hashable {

    /// Display filename, surfaced to the user and inlined into the issue body.
    public let filename: String

    /// MIME type, e.g. `image/png`.
    public let mimeType: String

    /// Raw bytes. Must fit within the relay's per-attachment limit (5 MB in v1).
    public let data: Data

    public init(filename: String, mimeType: String, data: Data) {
        self.filename = filename
        self.mimeType = mimeType
        self.data = data
    }
}

/// A user-authored report ready for submission.
///
/// Most fields are filled in by the SDK's built-in UI. Use the convenience
/// initializer when building reports programmatically from your own UI.
public struct Report: Sendable {

    /// What kind of report this is.
    public var kind: ReportKind

    /// The issue title that will appear on GitHub. Required.
    public var title: String

    /// The free-form body text. Combined with the diagnostics blob (when
    /// ``includeDiagnostics`` is true) and any inlined attachment URLs to
    /// produce the final markdown body posted to GitHub.
    public var body: String

    /// Optional PNG screenshot bytes.
    public var screenshot: Data?

    /// Additional attachments (currently images only).
    public var attachments: [ReportAttachment]

    /// Whether to append the diagnostics blob to the body.
    public var includeDiagnostics: Bool

    /// Stable per-install identifier used for per-device rate limiting and
    /// Phase 2 "My Issues" correlation. Generated by the SDK; surfaced
    /// publicly so callers using the programmatic ``GitTickets/submit(_:)``
    /// entry point can override.
    public var deviceID: String

    /// Opaque identifier for this submission. Embedded as
    /// `<!-- gittickets-id: UUID -->` in the issue body so the SDK can
    /// correlate it back to a created issue. Generated by the SDK.
    public var submissionID: UUID

    /// Memberwise initializer. `submissionID` defaults to a fresh UUID.
    /// `deviceID` defaults to the empty string (the SDK fills it in before
    /// submission if blank).
    public init(
        kind: ReportKind,
        title: String,
        body: String,
        screenshot: Data? = nil,
        attachments: [ReportAttachment] = [],
        includeDiagnostics: Bool = true,
        deviceID: String = "",
        submissionID: UUID = UUID()
    ) {
        self.kind = kind
        self.title = title
        self.body = body
        self.screenshot = screenshot
        self.attachments = attachments
        self.includeDiagnostics = includeDiagnostics
        self.deviceID = deviceID
        self.submissionID = submissionID
    }
}

/// The result of a successful ``GitTickets/submit(_:)`` call.
///
/// Also the row shape rendered by ``GitTicketsMyIssuesView`` for past
/// submissions.
public struct SubmittedIssue: Sendable, Identifiable, Hashable {

    /// Matches ``Report/submissionID`` of the originating report.
    public let id: UUID

    /// GitHub issue number (`#42`).
    public let issueNumber: Int

    /// HTTPS URL to the issue on github.com.
    public let issueURL: URL

    /// Issue title at creation time.
    public let title: String

    /// When the issue was created on GitHub.
    public let createdAt: Date

    /// Most recent comment timestamp, if any. Drives the "new reply" badge.
    public var latestReplyAt: Date?

    /// Total comments on the issue.
    public var replyCount: Int

    /// Comments the user has not yet seen in the in-app "My Issues" view.
    public var unreadReplyCount: Int

    public init(
        id: UUID,
        issueNumber: Int,
        issueURL: URL,
        title: String,
        createdAt: Date,
        latestReplyAt: Date? = nil,
        replyCount: Int = 0,
        unreadReplyCount: Int = 0
    ) {
        self.id = id
        self.issueNumber = issueNumber
        self.issueURL = issueURL
        self.title = title
        self.createdAt = createdAt
        self.latestReplyAt = latestReplyAt
        self.replyCount = replyCount
        self.unreadReplyCount = unreadReplyCount
    }
}
