import Foundation

/// The category of report being filed.
///
/// Drives the default body template (e.g. "Steps to reproduce" for `.bug`,
/// "Problem to solve" for `.featureRequest`) and the labels applied to the
/// resulting GitHub issue.
public enum ReportKind: String, Sendable, Hashable, CaseIterable, Codable {
    case bug
    case featureRequest = "feature_request"
    case question
}

/// A single attachment included with a ``Report``.
///
/// Currently used for inline images (PNG, JPEG, HEIC). Other types are
/// rejected by the relay in v1.
public struct ReportAttachment: Sendable, Hashable {

    /// Display filename, surfaced to the user and inlined into the issue body.
    public let filename: String

    /// MIME type, e.g. `image/png`.
    public let mimeType: String

    /// Raw bytes. Must fit within the relay's per-attachment limit (5 MB in v1).
    public let data: Data

    public init(filename: String, mimeType: String, data: Data) {
        self.filename = filename
        self.mimeType = mimeType
        self.data = data
    }
}

/// A user-authored report ready for submission.
///
/// Most fields are filled in by the SDK's built-in UI. Use the convenience
/// initializer when building reports programmatically from your own UI.
public struct Report: Sendable {

    /// What kind of report this is.
    public var kind: ReportKind

    /// The issue title that will appear on GitHub. Required.
    public var title: String

    /// The free-form body text. Combined with the diagnostics blob (when
    /// ``includeDiagnostics`` is true) and any inlined attachment URLs to
    /// produce the final markdown body posted to GitHub.
    public var body: String

    /// Optional PNG screenshot bytes.
    public var screenshot: Data?

    /// Additional attachments (currently images only).
    public var attachments: [ReportAttachment]

    /// Whether the form (or programmatic caller) wants diagnostics included.
    /// Informational — does NOT cause the submitter to re-collect diagnostics
    /// at submit time. See ``diagnosticsBlob``.
    public var includeDiagnostics: Bool

    /// Pre-collected, pre-redacted diagnostics text the user reviewed in the
    /// form. The submitter inlines this verbatim into the issue body — it is
    /// NEVER recollected at submit time. This is the critical "what the user
    /// sees == what gets sent" invariant.
    ///
    /// Programmatic callers using ``GitTickets/submit(_:)`` directly should
    /// populate this via ``DiagnosticsCollector`` (or leave `nil` to skip
    /// the diagnostics section in the body).
    public var diagnosticsBlob: String?

    /// Stable per-install identifier used for per-device rate limiting and
    /// Phase 2 "My Issues" correlation. Generated by the SDK; surfaced
    /// publicly so callers using the programmatic ``GitTickets/submit(_:)``
    /// entry point can override.
    public var deviceID: String

    /// Opaque identifier for this submission. Embedded as
    /// `<!-- gittickets-id: UUID -->` in the issue body so the SDK can
    /// correlate it back to a created issue. Generated by the SDK.
    public var submissionID: UUID

    /// Memberwise initializer. `submissionID` defaults to a fresh UUID.
    /// `deviceID` defaults to the empty string (the SDK fills it in before
    /// submission if blank).
    public init(
        kind: ReportKind,
        title: String,
        body: String,
        screenshot: Data? = nil,
        attachments: [ReportAttachment] = [],
        includeDiagnostics: Bool = true,
        diagnosticsBlob: String? = nil,
        deviceID: String = "",
        submissionID: UUID = UUID()
    ) {
        self.kind = kind
        self.title = title
        self.body = body
        self.screenshot = screenshot
        self.attachments = attachments
        self.includeDiagnostics = includeDiagnostics
        self.diagnosticsBlob = diagnosticsBlob
        self.deviceID = deviceID
        self.submissionID = submissionID
    }

    /// Convenience initializer for programmatic callers that have a
    /// ``DiagnosticsCollector`` blob in hand. Pulls the redacted `.text` out
    /// of the structured ``DiagnosticsBlob`` so callers can't accidentally
    /// pass `String(describing: blob)` and leak pre-redaction fields.
    init(
        kind: ReportKind,
        title: String,
        body: String,
        screenshot: Data? = nil,
        attachments: [ReportAttachment] = [],
        diagnostics: DiagnosticsBlob?,
        deviceID: String = "",
        submissionID: UUID = UUID()
    ) {
        self.init(
            kind: kind,
            title: title,
            body: body,
            screenshot: screenshot,
            attachments: attachments,
            includeDiagnostics: diagnostics != nil,
            diagnosticsBlob: diagnostics?.text,
            deviceID: deviceID,
            submissionID: submissionID
        )
    }
}

/// The result of a successful ``GitTickets/submit(_:)`` call.
///
/// Also the row shape rendered by ``GitTicketsMyIssuesView`` for past
/// submissions.
public struct SubmittedIssue: Sendable, Identifiable, Hashable {

    /// Matches ``Report/submissionID`` of the originating report.
    public let id: UUID

    /// GitHub issue number (`#42`).
    public let issueNumber: Int

    /// HTTPS URL to the issue on github.com.
    public let issueURL: URL

    /// Issue title at creation time.
    public let title: String

    /// When the issue was created on GitHub.
    public let createdAt: Date

    /// Most recent comment timestamp, if any. Drives the "new reply" badge.
    public var latestReplyAt: Date?

    /// Total comments on the issue.
    public var replyCount: Int

    /// Comments the user has not yet seen in the in-app "My Issues" view.
    public var unreadReplyCount: Int

    /// Labels that were requested but did not appear on the created GitHub
    /// issue. Common cause: a Device-Flow user who lacks `Issues: write`
    /// permission on the target repo — GitHub silently drops the labels
    /// from the create request. Empty array means every requested label
    /// stuck.
    ///
    /// `nil` means the relay did not report which labels stuck (older
    /// relays). Callers that depend on label filtering for "My Issues"
    /// correlation should treat `nil` as "unknown" rather than "all stuck".
    public var missingLabels: [String]?

    public init(
        id: UUID,
        issueNumber: Int,
        issueURL: URL,
        title: String,
        createdAt: Date,
        latestReplyAt: Date? = nil,
        replyCount: Int = 0,
        unreadReplyCount: Int = 0,
        missingLabels: [String]? = nil
    ) {
        self.id = id
        self.issueNumber = issueNumber
        self.issueURL = issueURL
        self.title = title
        self.createdAt = createdAt
        self.latestReplyAt = latestReplyAt
        self.replyCount = replyCount
        self.unreadReplyCount = unreadReplyCount
        self.missingLabels = missingLabels
    }
}

/// One comment on a GitHub issue, as surfaced by ``IssueDetailView``.
///
/// Markdown content lives in ``body``; the rendering layer is responsible for
/// turning it into something a SwiftUI ``Text`` view can display.
///
/// `Hashable + Identifiable` so SwiftUI lists can diff comment arrays
/// without an explicit `id:` key path.
public struct IssueComment: Sendable, Hashable, Identifiable {

    /// GitHub's per-comment identifier.
    public let id: Int

    /// The author's GitHub login (e.g. `"alanw"`). Empty when the comment was
    /// posted by a bot or when the relay omits the author for privacy reasons.
    public let author: String

    /// Raw markdown body, exactly as stored on GitHub. ``MarkdownCommentView``
    /// renders this through `AttributedString(markdown:)`.
    public let body: String

    /// When the comment was created on GitHub.
    public let createdAt: Date

    public init(id: Int, author: String, body: String, createdAt: Date) {
        self.id = id
        self.author = author
        self.body = body
        self.createdAt = createdAt
    }

    /// Markdown alias for the redesigned view layer that uses
    /// ``bodyMarkdown`` rather than ``body``. Backed by the same bytes.
    public var bodyMarkdown: String { body }

    /// Whether the comment author is recognized as a repo maintainer.
    /// Always `false` in v1.x — the relay doesn't surface GitHub
    /// collaborator membership and we don't probe it locally. A future
    /// relay schema bump can wire this; consumers may treat as a hint.
    public var isMaintainer: Bool { false }
}

/// The locally-cached, as-submitted report rendered by ``IssueDetailView``'s
/// "Your report" card.
///
/// Returned by ``GitTickets/cachedReport(for:)``. The ``body`` is the user's
/// authored text with the diagnostics block, attachments section, inline
/// screenshot, and correlation marker stripped — exactly what they typed.
public struct CachedReport: Sendable, Hashable {

    /// Bug / feature request / question.
    public let kind: ReportKind

    /// User-authored body, stripped of diagnostics + marker.
    public let body: String

    /// When the SDK submitted the report locally (precedes GitHub's
    /// `created_at` by however long the round-trip took).
    public let submittedAt: Date

    /// Whether the body that landed on GitHub carried a diagnostics
    /// section. Drives the "Diagnostics attached" affordance in the
    /// report card. Derived from the cached body at lookup time so the
    /// flag matches what's actually on GitHub.
    public let includedDiagnostics: Bool

    public init(kind: ReportKind, body: String, submittedAt: Date, includedDiagnostics: Bool) {
        self.kind = kind
        self.body = body
        self.submittedAt = submittedAt
        self.includedDiagnostics = includedDiagnostics
    }
}
